version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/android:29.0.0
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run:
          name: checking storage
          command: df -h
      - run:
          name: build environment
          command: |
            DEBIAN_FRONTEND=noninteractive apt-get --quiet update && apt-get --quiet install git aria2 apt-utils -y
            git clone https://github.com/boedhack99/scripts --depth=1 --branch master
            bash scripts/setup/android_build_env.sh >/dev/null
            bash scripts/setup/install_android_sdk.sh >/dev/null
      - run:
          name: Clone
          command: |
            repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-18.1 -g default,-device,-mips,-darwin,-notdefault
            git clone https://github.com/boedhack/local_manifest.git --depth=1 -b 11 .repo/local_manifests
            repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - run:
          name: Build
          command: ./build.sh
      - store_artifacts:
          path: out/target/product/mojito/test.zip
          destination: test.zip
