version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/android:30.0
    steps:
      - checkout
      - run:
          name: Checking Free Space
          command: df -h && echo "Cores = $(nproc --all)" && echo "Ram = $(free -h)"
      - run:
          name: Building environment
          command: |
            echo "Configuring git"
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "boedhack99"
            git config --global color.ui "true"
            echo "git identity setup successfully!"
            git clone https://github.com/boedhack99/scripts --depth=1 --single-branch
            cd scripts
            sudo -E bash setup/android_build_env.sh
            sudo -E bash setup/install_android_sdk.sh
      - run:
          name: Cloning repo
          command: |
            repo init --depth=1 --no-repo-verify -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11 -g default,-device,-mips,-darwin,-notdefault
            git clone https://github.com/boedhack99/local_manifest.git --depth=1 -b main .repo/local_manifests
            repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j4
      - run:
          name: Building
          command: |
            . build/envsetup.sh
            lunch twrp_mojito-eng
            export ALLOWS_MISSING_DEPENDENCIES="true"
            repo sync -j4
            mka bootimage
      - store_artifacts:
          path: out/target/product/mojito/boot.img
          destination: boot.img
