version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: fr3akyphantom/droid-builder:focal
    steps:
      - checkout
      - run:
          name: Checking Free Space
          command: df -h && echo "Cores = $(nproc --all)" && echo "Ram = $(free -h)"
      - run:
          name: Building environment
          command: |
            echo "Configuring git"
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "boedhack99"
            git config --global color.ui "true"
            echo "git identity setup successfully!"
      - run:
          name: Cloning repo
          command: |
            mkdir android && cd android
            repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-18.1 -g default,-device,-mips,-darwin,-notdefault
            git clone https://github.com/boedhack/local_manifest.git --depth=1 -b 11 .repo/local_manifests
            repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - run:
          name: Building
          command: |
            source build/envsetup.sh
            lunch lineage_mojito-userdebug
            export ALLOWS_MISSING_DEPENDENCIES="true"
            mka bacon
      - store_artifacts:
          path: out/target/product/mojito/ROM_test.zip
          destination: ROM_test.zip
