version: 2.1
jobs:
  build:
    working_directory: ~/tmp/rom
    docker:
      - image: cimg/android:2022.09.2
    steps:
      - checkout
      - run:
          name: Checking Free Space
          command: df -h && echo "Cores = $(nproc --all)" && echo "Ram = $(free -h)"
      - run:
          name: Download ccache
          command: |
            sudo  apt install aria2 ccache gzip pigz rclone -y
            cd /tmp
            #time aria2c $ccache -x16 -s50
            #time tar xf ccache.tar.gz
            #rm -rf ccache.tar.gz
      - run:
          name: Building environment
          command: |
            echo "Configuring git"
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "boedhack99"
            git config --global color.ui "true"
            echo "git identity setup successfully!"
            git clone https://github.com/boedhack99/scripts --depth=1 --single-branch
            cd scripts
            sudo -E bash setup/android_build_env.sh
            sudo -E bash setup/install_android_sdk.sh
      - run:
          name: Cloning repo
          command: |
            repo init --depth=1 --no-repo-verify -u https://github.com/Evolution-X/manifest -b tiramisu
            git clone https://github.com/boedhack99/local_manifest.git --depth=1 -b fog-13 .repo/local_manifests
            repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j4
      - run:
          name: Building
          command: |
            . build/envsetup.sh
            lunch evolution_fog-userdebug
            export ALLOW_MISSING_DEPENDENCIES=true
            export CCACHE_DIR=/tmp/ccache
            export CCACHE_EXEC=$(which ccache)
            export USE_CCACHE=1
            export ANDROID_JACK_VM_ARGS="-Xmx8g -Dfile.encoding=UTF-8 -XX:+TieredCompilation"
            ccache -M 20G 
            ccache -o compression=true
            ccache -z
            make sepolicy
      - store_artifacts:
          path: out/target/product/mojito/lineage-mojito.zip
          destination: lineage-mojito.zip
